# Generated by Django 3.0.3 on 2020-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_docente_progetto_studente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='matricola',
            field=models.CharField(max_length=10),
        ),
    ]
