# Generated by Django 3.0.3 on 2020-03-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('cognome', models.CharField(max_length=500)),
                ('mail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AttProgettuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=1000)),
                ('is_taken', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Docente')),
            ],
        ),
    ]
