# Generated by Django 3.0.4 on 2020-04-04 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesiArchiviata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlatore', models.CharField(max_length=100)),
                ('argomento', models.CharField(max_length=500)),
                ('tirocinio_interno', models.BooleanField(default=False)),
                ('tirocinio_azienda', models.BooleanField(default=False)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Tesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlatore', models.CharField(max_length=100)),
                ('argomento', models.CharField(max_length=500)),
                ('tirocinio_interno', models.BooleanField(default=False)),
                ('tirocinio_azienda', models.BooleanField(default=False)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta_tesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatore', models.CharField(max_length=100)),
                ('correlatore', models.CharField(max_length=100)),
                ('argomento', models.CharField(max_length=500)),
                ('tirocinio_interno', models.BooleanField(default=False)),
                ('tirocinio_azienda', models.BooleanField(default=False)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Studente')),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta_prova_finale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=100)),
                ('argomento', models.CharField(max_length=500)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Studente')),
            ],
        ),
        migrations.CreateModel(
            name='Attivita_progettuale_Archiviata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argomento', models.CharField(max_length=500)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Attivita_progettuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argomento', models.CharField(max_length=500)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
    ]
