# Generated by Django 3.0.3 on 2020-03-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studente',
        ),
    ]
