# Generated by Django 3.0.3 on 2020-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_studente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('cognome', models.CharField(max_length=500)),
                ('matricola', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=1000)),
            ],
        ),
    ]
