# Generated by Django 3.0.3 on 2020-03-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200322_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='matricola',
        ),
    ]
