# Generated by Django 3.0.3 on 2020-03-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_docente_matricola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progetto',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Studente',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Progetto',
        ),
    ]
