# Generated by Django 3.0.3 on 2020-03-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_profile'),
        ('home', '0010_auto_20200322_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlatore', models.CharField(max_length=100)),
                ('argomento', models.CharField(max_length=500)),
                ('tirocinio', models.BooleanField(default=False)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('relatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Attivita_progettuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argomento', models.CharField(max_length=500)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('tag', models.IntegerField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Docente')),
            ],
        ),
    ]
