# Generated by Django 3.0.3 on 2020-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_attivita_progettuale_tesi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesi',
            old_name='tirocinio',
            new_name='tirocinio_azienda',
        ),
        migrations.AddField(
            model_name='tesi',
            name='tirocinio_interno',
            field=models.BooleanField(default=False),
        ),
    ]
